### ISSUE TITLE
`npm test` does not work

### ISSUE THREAD

**Issue by jgable** [jgable/cache-swap#10]
@shinnn I'm trying to run the tests but I'm getting an error:

```
> cache-swap@0.2.3 pretest /Users/jgable/projects/cache-swap
> eslint --config @shinnn/node-legacy index.js test.js

/Users/jgable/projects/cache-swap/node_modules/eslint/lib/config/config-file.js:172
        throw e;
              ^
TypeError: Cannot read config package: @shinnn/eslint-config-node-legacy
Error: undefined is not a function
    at Object.<anonymous> (/Users/jgable/projects/cache-swap/node_modules/@shinnn/eslint-config-node-legacy/index.js:3:8)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at loadPackage (/Users/jgable/projects/cache-swap/node_modules/eslint/lib/config/config-file.js:168:16)
    at loadConfigFile (/Users/jgable/projects/cache-swap/node_modules/eslint/lib/config/config-file.js:212:18)
    at Object.load (/Users/jgable/projects/cache-swap/node_modules/eslint/lib/config/config-file.js:385:18)
npm ERR! Test failed.  See above for more details.
```

I've tried with node 0.12 and 0.14, npm version 3.3.12.  Nuked my node_modules folder and re-installed and still having problems.  I have eslint installed globally as well.

**Comment by shinnn** [comment]
Reinstall `eslint-config-node-legacy` and the problem will be fixed.
