### ISSUE TITLE
Warning: a promise was created in a  handler but was not returned from it

### ISSUE THREAD

**Issue by kilianc** [jgable/cache-swap#9]
```
Warning: a promise was created in a  handler but was not returned from it
    at /Volumes/WS/forks/gulp-cache/node_modules/cache-swap/index.js:46:7
```

prepping a PR

**Comment by kilianc** [comment]
I actually have no idea how to fix this, bluebird is not even a dep :S 

```
Warning: a promise was created in a  handler but was not returned from it
    at /Volumes/WS/forks/gulp-cache/node_modules/cache-swap/index.js:46:7
    at /Volumes/WS/forks/gulp-cache/node_modules/graceful-fs/graceful-fs.js:76:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
```

**Comment by jgable** [comment]
Probably just need to update the graceful-SF dependency, or whatever is
using it. I'll check it out today.
